# Numpy Examples

## 1) Computation with arrays

### a) Sigmoid activation function of a vector

In [7]:
import numpy as np
x = np.array([4, -1, 7, 9, 3, -5])

**Apply the Sigmoid activation function: $y = sigmoid(x)$**
$$sigmoid(x_i) = \frac{1}{1+exp(-x_i)}$$


In [8]:
y = 1/(1+np.exp(-x))
y

array([0.98201379, 0.26894142, 0.99908895, 0.99987661, 0.95257413,
       0.00669285])

### b) Softmax activation function

Activation function that normalizes the input vector (z) to a discrete probability distribution (values of the result add to 1).

$$y_i = \frac{exp(x_i)}{\sum_j{exp(x_j)}}$$

In [9]:
y = np.exp(x)/(np.sum(np.exp(x)))
y

array([5.88673555e-03, 3.96645122e-05, 1.18238244e-01, 8.73669020e-01,
       2.16560899e-03, 7.26480881e-07])

## 2) Broadcasting: dataset normalization

In [11]:
# Input table
n_samples = 100
n_columns = 5
mean = 1
std = 3
X = np.random.normal(mean, std, (n_samples, n_columns))

** Apply z-score: normalize each column by subtracting its mean and dividing by its standard deviation **

In [19]:
(X-mean)/std

array([[-1.58207380e+00,  8.98648944e-01, -1.14659092e+00,
         2.32692422e-01, -7.78127791e-01],
       [ 2.43231557e-01,  6.27688308e-01, -6.40188457e-01,
        -4.94481626e-01,  1.17940562e+00],
       [-4.09387926e-01,  2.11468326e+00,  6.15866401e-01,
         1.42126040e-01, -5.73309270e-01],
       [ 1.19236504e+00, -1.20129498e+00,  5.69369569e-01,
         1.17941897e+00,  5.72731153e-01],
       [-6.30719732e-01,  6.95867867e-01, -4.80238397e-01,
        -5.23983632e-01, -8.35322342e-01],
       [-9.22361238e-02,  7.95725854e-02,  1.35780598e+00,
        -1.84706651e+00, -1.79671061e+00],
       [-7.91636934e-02,  7.39110642e-01,  3.11617994e-01,
         2.60595293e-01, -1.30191007e+00],
       [-6.22296566e-01, -1.73338943e+00, -4.55389017e-01,
        -2.13373268e-01,  1.46538225e+00],
       [-9.50915914e-02,  1.36643466e+00, -2.24359794e+00,
         1.15345257e+00, -4.36669375e-01],
       [ 4.11030320e-01,  6.19916014e-01, -3.74217750e-01,
         4.14966174e-01

## 3) Accessing Numpy Arrays

In [20]:
#Input data
import numpy as np

# Input table (12 samples x 4 attributes)
X = np.array([[5.1, 3.5, 1.4, 0.2],
           [4.3, 3. , 1.1, 0.1],
           [5. , 3.4, 1.6, 0.4],
           [5.1, 3.4, 1.5, 0.2],
           [6.9, 3.1, 4.9, 1.5],
           [6.7, 3.1, 4.4, 1.4],
           [6. , 2.9, 4.5, 1.5],
           [6.1, 3. , 4.6, 1.4],
           [6.5, 3. , 5.8, 2.2],
           [7.7, 3.8, 6.7, 2.2],
           [7.4, 2.8, 6.1, 1.9],
           [6.8, 3.2, 5.9, 2.3]])
# Column names
columns = ['height','width','intensity','weight']

# Class label of each sample
labels = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2])

In [21]:
X.shape, labels.shape

((12, 4), (12,))

In [22]:
# Get column indices
height_i = columns.index('height')
intensity_i = columns.index('intensity')

**Compute the average height:**

In [23]:
X[:, height_i].mean()

6.133333333333334

**Compute the average height of samples with intensity greater than 5:**

In [24]:
mask = X[:, intensity_i]>5 # this is a mask of values with intensity > 5
X[mask, height_i].mean() # We pass the mask on the rows and the the index of height feature on the column

7.1000000000000005

**Compute the probability of class 2 if intensity>5**
$$p = \frac{\#(intensity>5 \land class2)}{\#(intensity>5)}$$

In [25]:
# If we talk about classes -> y/labels arraya
d = (X[:, intensity_i] > 5).sum() # we sum ones with zeroes

n=((X[:, intensity_i] > 5)&(labels==2)).sum()

p = n/d

p


0.75

**Print the height of the top 3 records with highest intensity:**

In [26]:
np.sort(X[:, intensity_i], axis=0)[-3:]

X[np.argsort(X, axis=0)[:, intensity_i][-3:]]

np.argsort(X[:,intensity_i])[-3:]

array([11, 10,  9])